# Generated by Django 4.2 on 2023-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50)),
                ('vaqt', models.TimeField()),
                ('izoh', models.TextField()),
                ('maqsad', models.CharField(max_length=50)),
            ],
        ),
    ]
